ARTISTS = [
    "Ada Clemente",
    "Adria Gonzalez Marin",
    "Adrian Yelamos",
    "Aida Pi",
    "Aina Castane",
    "Ainara Guell",
    "Al Gonzalez",
    "Albert Cobacho",
    "Aleix Mataro",
    "Alejandra Baelo",
    "Alejandro Camarena",
    "Alex Garcia",
    "Alex Martinez",
    "Alliestair Casis",
    "Alvaro Garcia",
    "Ana Vera",
    "Anna Bitlloch",
    "Anna Povea",
    "Antonio Santamaria",
    "Arly Jones",
    "Arturo Correa",
    "Avril Moreno",
    "Carles Prenafeta",
    "Carolina Novell",
    "Caterina Alfaro",
    "Celia Esteve",
    "Clara Daenen",
    "Clara Erraez",
    "Claudia Ciller",
    "Claudia Duarte",
    "Dafne Hervatin",
    "Daniel Lopez",
    "Daniel Troya",
    "David Anaya",
    "David Campoy",
    "David Nebot",
    "Ekaterina Kravchenko",
    "Elena Pou",
    "Emilio Aycaguer",
    "Eric Larrucea Valles",
    "Esteve Garriga",
    "Eva Huarte",
    "Fran Ezquerro",
    "Francisco Ramirez",
    "Guido Del Solar",
    "Guillem Santacreu",
    "Irene Godoy",
    "Irene Loscos",
    "Isadora Gonzaga",
    "Ivan Gimenez",
    "Jan Manero Fabregat",
    "Jana Gaya",
    "Jeremias Garcia",
    "Jianlan Camarasa",
    "Josu Puente",
    "Julia Pareja",
    "Julia Pitarch",
    "Julian Villanua",
    "Karyna Miakshykava",
    "Laia Torrent",
    "Laura Cortes",
    "Layra Cocke",
    "Livia Coronel",
    "Lucia Ezquerro",
    "Lucia Rivera",
    "Luna Zhou",
    "Mafalda Santamaria",
    "Mar Llado",
    "Marc Dominguez Martin",
    "Marc Rodriguez",
    "Marc Sole",
    "Maria-Alexandrovna Pavlova",
    "Mario Caseny",
    "Mario Santamaria",
    "Marta Benito",
    "Marta Cai",
    "Marta Martinez",
    "Marti Oliu",
    "Melania Santamaria",
    "Miquel Aloy",
    "Miriam Hidalgo",
    "Nicolas Fernandez",
    "Nicole Liarte Jizbova",
    "Norma De Haro",
    "Nuria Garcia",
    "Nuria Grifols",
    "Omar Fernandez",
    "Ona Alonso",
    "Onia Bofarull",
    "Oriol Pomar",
    "Oscar Chuecos",
    "Oscar Gamell",
    "Pablo Garcia",
    "Pablo Mendelbaum",
    "Pau Marquez",
    "Pol Garcia",
    "Polina Kotova",
    "Rafael Moreno",
    "Rafater",
    "Roc Esquius"
]

LEADS = [
    "David Nebot",
    "Esteve Garriga",
    "Isadora Gonzaga",
    "Julian Villanua",
    "Miquel Aloy",
    "Miriam Hidalgo",
    "Nuria Altabella",
    "Omar Fernandez",
    "Oscar Chuecos",
    "Pablo Mendelbaum",
    "Rafater",
    "Roc Esquius"
]