ARTISTS = [
    "Stepan Batllori Martinez",
    "Ariadna Cañagueral Rosell",
    "JuanPablo Fuentes Ruiz",
    "Ivan Batllori Martinez",
    "Ada Clemente",
    "Adria Gonzalez Marin",
    "Adrian Yelamos",
    "Aida Pi",
    "Aina Castane",
    "Ainara Guell",
    "Al Gonzalez",
    "Albert Cobacho",
    "Aleix Mataro",
    "Alejandra Baelo",
    "Alejandro Camarena",
    "Alex Garcia",
    "Alliestair Casis",
    "Ana Vera",
    "Anna Bitlloch",
    "Anna Povea",
    "Antonio Santamaria",
    "Arly Jones",
    "Arturo Correa",
    "Avril Moreno",
    "Carles Prenafeta",
    "Carolina Novell",
    "Caterina Alfaro",
    "Celia Esteve",
    "Clara Daenen",
    "Clara Erraez",
    "Claudia Ciller",
    "Claudia Duarte",
    "Dafne Hervatin",
    "Daniel Lopez",
    "Daniel Troya",
    "David Anaya",
    "David Campoy",
    "Ekaterina Kravchenko",
    "Elena Pou",
    "Emilio Aycaguer",
    "Eric Larrucea Valles",
    "Eva Huarte",
    "Fran Ezquerro",
    "Francisco Ramirez",
    "Guido Del Solar",
    "Guillem Santacreu",
    "Irene Godoy",
    "Irene Loscos",
    "Ivan Gimenez",
    "Jan Manero Fabregat",
    "Jana Gaya",
    "Jeremias Garcia",
    "Jianlan Camarasa",
    "Josu Puente",
    "Julia Pareja",
    "Julia Pitarch",
    "Karyna Miakshykava",
    "Laia Torrent",
    "Laura Cortes",
    "Layra Cocke",
    "Livia Coronel",
    "Lucia Ezquerro",
    "Lucia Rivera",
    "Luna Zhou",
    "Mafalda Santamaria",
    "Mar Llado",
    "Marc Dominguez Martin",
    "Marc Rodriguez",
    "Marc Sole",
    "Maria-Alexandrovna Pavlova",
    "Mario Caseny",
    "Mario Santamaria",
    "Marta Benito",
    "Marta Cai",
    "Marta Martinez",
    "Marti Oliu",
    "Melania Santamaria",
    "Nicolas Fernandez",
    "Nicole Liarte Jizbova",
    "Norma De Haro",
    "Nuria Garcia",
    "Nuria Grifols",
    "Ona Alonso",
    "Onia Bofarull",
    "Oriol Pomar",
    "Oscar Gamell",
    "Pablo Garcia",
    "Pau Marquez",
    "Pol Garcia",
    "Polina Kotova",
    "Rafael Moreno"
]

LEADS = [
    "David Nebot",
    "Esteve Garriga",
    "Isadora Gonzaga",
    "Julian Villanua",
    "Miquel Aloy",
    "Miriam Hidalgo",
    "Nuria Altabella",
    "Omar Fernandez",
    "Oscar Chuecos",
    "Pablo Mendelbaum",
    "Rafater",
    "Roc Esquius",
    "Alex Martinez",
    "Alvaro Garcia"
]